"use strict";
const csrf=document.querySelector('meta[name="sqliblind-csrf"]').content;
const state={scanId:null,scan:null,entities:new Map(),relationships:new Map(),events:[],activities:new Map(),source:null,filter:""};
const $=id=>document.getElementById(id);
const terminal=new Set(["completed","failed","cancelled","interrupted"]);
function toast(message){const node=$("toast");node.textContent=message;node.classList.add("show");setTimeout(()=>node.classList.remove("show"),2200)}
async function api(path,options={}){const headers={...(options.headers||{})};if(options.method&&options.method!=="GET")headers["X-SQLIBLIND-CSRF"]=csrf;if(options.body&&!headers["Content-Type"])headers["Content-Type"]="application/json";const response=await fetch(path,{...options,headers});if(!response.ok){let message=`HTTP ${response.status}`;try{const body=await response.json();message=body.detail||message}catch{}throw new Error(message)}return response}
function parseLines(value,separator){const out={};for(const line of value.split(/\r?\n/)){if(!line.trim()||!line.includes(separator))continue;const index=line.indexOf(separator);out[line.slice(0,index).trim()]=line.slice(index+1).trim()}return out}
function formPayload(form){const data=new FormData(form),get=name=>String(data.get(name)||"").trim(),number=(name,fallback)=>{const value=get(name);return value?Number(value):fallback};return{url:get("url"),parameter:get("parameter")||"id",url_template:get("url_template")||null,dialect:get("dialect"),oracle:get("oracle"),true_statuses:get("true_statuses")||"200",true_marker:get("true_marker")||null,true_regex:get("true_marker")||null,true_length:get("true_length")?Number(get("true_length")):null,length_tolerance:number("length_tolerance",0),timeout:number("timeout",10),retries:1,delay:number("delay",.1),max_requests:number("max_requests",5000),workers:number("workers",4),max_length:number("max_length",128),max_items:number("max_items",128),min_char_code:32,max_char_code:126,headers:parseLines(get("headers"),":"),cookies:parseLines(get("cookies"),"="),proxy:get("proxy")||null,insecure:data.has("insecure"),skip_calibration:data.has("skip_calibration"),include_data:data.has("include_data"),data_tables:get("data_tables"),max_rows:number("max_rows",5),max_data_columns:number("max_data_columns",10),max_value_length:number("max_value_length",128),max_data_bytes:number("max_data_bytes",10000),reveal_sensitive_values:data.has("reveal_sensitive_values")}}
async function refreshSessions(){const scans=await(await api("/api/scans")).json();const root=$("sessions");root.replaceChildren();for(const scan of scans){const item=document.createElement("div");item.className="session"+(scan.id===state.scanId?" selected":"");item.dataset.id=scan.id;const title=document.createElement("strong");title.textContent=`${scan.id.slice(0,8)} · ${scan.status}`;const target=document.createElement("small");target.textContent=scan.config.url||scan.config.url_template||"target";item.append(title,target);item.addEventListener("click",()=>selectScan(scan.id));root.append(item)}}
function resetScan(){state.entities.clear();state.relationships.clear();state.events=[];state.activities.clear();renderAll()}
async function selectScan(id){state.scanId=id;resetScan();if(state.source)state.source.close();const snapshot=await(await api(`/api/scans/${id}/snapshot`)).json();state.scan=snapshot.scan;for(const entity of snapshot.entities)state.entities.set(entity.id,entity);for(const relation of snapshot.relationships)state.relationships.set(relation.id,relation);for(const activity of snapshot.activities||[])state.activities.set(activity.id,activity);const events=await(await api(`/api/scans/${id}/events?after=0&limit=5000`)).json();for(const event of events)applyEvent(event,false);renderAll();connectStream(events.length?events[events.length-1].seq:0);refreshSessions()}
function applyActivity(type,activity){if(!activity||!activity.id)return;state.activities.set(activity.id,{...(state.activities.get(activity.id)||{}),...activity,event:type});}
function applyEvent(item,render=true){if(state.events.some(event=>event.seq===item.seq))return;state.events.push(item);const payload=item.payload||{};if(payload.entity)state.entities.set(payload.entity.id,{...(state.entities.get(payload.entity.id)||{}),...payload.entity});if(payload.relationship)state.relationships.set(payload.relationship.id,payload.relationship);if(item.event.startsWith('activity.'))applyActivity(item.event,payload.activity);if(item.event==="phase.started")$("activityPhase").textContent=payload.phase||"working";if(item.event==="phase.completed")$("activityPhase").textContent=`${payload.phase||"phase"} complete`;if(item.event.startsWith("scan."))refreshScan();if(render)renderAll()}
function connectStream(after){if(!state.scanId)return;state.source=new EventSource(`/api/scans/${state.scanId}/stream?after=${after}`);state.source.onopen=()=>{$("connection").textContent="live";$("connection").className="status online"};state.source.onmessage=event=>applyEvent(JSON.parse(event.data));state.source.onerror=()=>{$("connection").textContent="reconnecting";$("connection").className="status"}}
async function refreshScan(){if(!state.scanId)return;state.scan=await(await api(`/api/scans/${state.scanId}`)).json();renderMetrics();if(terminal.has(state.scan.status)){setTimeout(refreshSessions,50)}}
function renderActivities(){const root=$("activityView");root.replaceChildren();const values=[...state.activities.values()].sort((a,b)=>(a.status==="running"?-1:1)-(b.status==="running"?-1:1)||String(b.id).localeCompare(String(a.id)));const shown=values.filter(item=>item.status==="running").concat(values.filter(item=>item.status!=="running").slice(0,4));if(!shown.length){root.innerHTML='<div class="empty">Waiting for extraction activity.</div>';return}for(const item of shown){const card=document.createElement("article");card.className="activity-card activity"+(item.status==="running"?"":" done");const operation=document.createElement("strong");operation.textContent=item.operation||"Working";const target=document.createElement("span");target.className="target";target.textContent=item.target||"location";const detail=document.createElement("span");detail.className="detail";detail.textContent=item.detail||item.status;const footer=document.createElement("footer");const worker=document.createElement("span");worker.textContent=item.worker||"worker";const timing=document.createElement("span");const count=item.current!==undefined?` · ${item.current}${item.maximum!==undefined?`/${item.maximum}`:""} ${item.unit||""}`:"";timing.textContent=`${Number(item.elapsed_seconds||0).toFixed(1)}s · ${item.requests_used||0} req${count}`;footer.append(worker,timing);card.append(operation,target,detail,footer);root.append(card)}}
function renderMetrics(){const counts={schema:0,table:0,column:0,row:0,cell:0};for(const entity of state.entities.values())if(entity.type in counts)counts[entity.type]++;const stats=state.scan?.stats||{};const values=[...Object.entries(counts),["requests",stats.requests||0],["status",state.scan?.status||"idle"]];$("metrics").replaceChildren();for(const [name,value] of values){const div=document.createElement("div");div.className="metric";const strong=document.createElement("strong");strong.textContent=String(value);div.append(strong,document.createTextNode(name));$("metrics").append(div)}}
function children(parent){return [...state.entities.values()].filter(entity=>(entity.parent_id||null)===(parent||null))}
function entityMatches(entity){const query=state.filter.toLowerCase();return !query||`${entity.type} ${entity.name} ${JSON.stringify(entity.data||{})}`.toLowerCase().includes(query)}
function treeNode(entity){const box=document.createElement("div");box.className="tree-node";const button=document.createElement("button");const kind=document.createElement("span");kind.className="kind";kind.textContent=entity.type.toUpperCase();button.append(kind,document.createTextNode(entity.name));button.addEventListener("click",()=>openDrawer(entity));box.append(button);for(const child of children(entity.id))if(entityMatches(child)||children(child.id).some(entityMatches))box.append(treeNode(child));return box}
function renderTree(){const root=$("treePane");root.replaceChildren();const roots=children(null).filter(entityMatches);if(!roots.length){root.innerHTML='<div class="empty">No matching entities.</div>';return}for(const entity of roots)root.append(treeNode(entity))}
function renderEntities(){const root=$("entities");root.replaceChildren();for(const entity of [...state.entities.values()].filter(entityMatches)){const card=document.createElement("article");card.className="entity-card";const title=document.createElement("strong");title.textContent=entity.name;const meta=document.createElement("small");meta.textContent=`${entity.type} » ${entity.status}`;card.append(title,meta);card.addEventListener("click",()=>openDrawer(entity));root.append(card)}}
function renderGraph(){const svg=$("graph"),entities=[...state.entities.values()].filter(entityMatches).slice(0,120);svf.replaceChildren();if(!entities.length)return;const width=Math.max(svg.clientWidth,600),height=560,byId=new Map(entities.map((entity,index)=>[entity.id,{entity,index}]));svg.setAttribute("viewBox",`0 0 ${width} ${height}`);for(const relation of state.relationships.values()){const source=byId.get(relation.source_id),target=byId.get(relation.target_id);if(!source||!target)continue;const line=document.createElementNS("http://www.w3.org/2000/svg","line");line.setAttribute("x1",String(80+(source.index%6)*(width-160)/5));line.setAttribute("y1",String(45+Math.floor(source.index/6)*65));line.setAttribute("x2",String(80+(target.index%6)*(width-160)/5));line.setAttribute("y2",String(45+Math.floor(target.index/6)*65));svg.append(line)}for(const {entity,index} of byId.values(){const x=80+(index%6)*(width-160)/5,y=45+Math.floor(index/6)*65;const group=document.createElementNS("http://www.w3.org/2000/svg","g");const circle=document.createElementNS(group.namespaceURI,"circle");circle.setAttribute("cx",String(x));circle.setAttribute("cy",String(y));circle.setAttribute("r","17");circle.setAttribute("fill",entity.type==="schema"?"#32689b":entity.type==="table"?"#8a6725":"#245f50");const text=document.createElementNS(group.namespaceURI,"text");text.setAttribute("x",String(x+22));text.setAttribute("y",String(y+4));text.textContent=entity.name.slice(0,24);group.append(circle,text);group.addEventListener("click",()=>openDrawer(entity));svg.append(group)}}
function renderEvents(){$("events").textContent=state.events.slice(-300).map(item=>`${item.seq} ${item.timestamp} ${item.event} ${JSON.stringify/item.payload)}`).join("\n")}
function renderAll(){renderActivities();renderMetrics();renderTree();renderEntities();renderGraph();renderEvents()}
function openDrawer(entity){$("drawerTitle").textContent=`${entity.type}: ${entity.name}`;const related=[...state.relationships.values()].filter(rel=>rel.source_id===entity.id||rel.target_id===entity.id);$("drawerBody").textContent=JSON.stringify({...entity,relationships:related},null,2);$("drawer").classList.add("open");$("drawer").setAttribute("aria-hidden","false")}
async function control(action){if(!state.scanId)return;await api(`/api/scans/${state.scanId}/${action}`, {method:"POST"});toast(action);refreshScan()}
$("scanForm").addEventListener("submit",async event=>{event.preventDefault();try{const response=await api("/api/scans",{method:"POST",body:JSON.stringify(formPayload(event.currentTarget))});const result=await response.json();await selectScan(result.id)}catch(error){toast(error.message)}});
$("pauseBtn").onclick=()=>control("pause");$("resumeBtn").onclick=()=>control("resume");$("stopBtn").onclick=()=>control("stop");$("exportBtn").onclick=()=>{if(state.scanId)location.href=`/api/scans/${state.scanId}/export?format=${$("exportFormat").value}`};$("filter").addEventListener("input",event=>{state.filter=event.target.value;renderAll()});$("drawerClose").onclick=()=>$("drawer").classList.remove("open");document.querySelectorAll("[data-pane]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-pane]").forEach(node=>node.classList.toggle("active",node===button));for(const name of ["tree","graph","entities","events"])$(`${name}Pane`).classList.toggle("hidden",name!==button.dataset.pane);renderGraph()}));
refreshSessions().catch(error=>toast(error.message));setInterval(()=>{if(state.scanId)refreshScan().catch(()=>{})},1500);
